"""empty message

Revision ID: 3364e0caddb7
Revises: 6ef04ffa4140
Create Date: 2020-03-06 08:33:12.549967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3364e0caddb7'
down_revision = '6ef04ffa4140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], [u'Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], [u'Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    
    op.drop_column('Artist', 'genres')
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    # ### end Alembic commands ###
